### ISSUE TITLE
 compiling gpu branch: 'filesystem' file not found

### ISSUE THREAD

**Issue by cbyrohl** [samridh-dev/votess#2]
Copying Dylan's issues over from the private repo:

> Compiling the current gpu branch with intel/2024.0 fails with
> 
> /u/dnelson/votess/test/votess.cpp:194:10: fatal error: 'filesystem' file not found
>   194 | #include <filesystem>
>       |          ^~~~~~~~~~~~
> 1 error generated.
> 

This seems to be a somewhat commonly occurring issue when using the intel compilers, would be great if you could find a fix for the CMakeLists.txt

**Comment by samridh-dev** [comment]
Is it possible if I could see which version of gcc and g++ you are using? Intel compilers do use a gcc/g++ backend, but g++ 7 does not have an implementation of <filesystem>.

Let me know if I should include an option specifying a backend gcc version.

There was also no need to include <filesystem> in test/votess.cpp, so I have removed it. Let me know if that was the only thing blocking compilation.

**Comment by cbyrohl** [comment]
I can confirm that the current branch now works with intel/2024.0 on the MCPDF vera cluster.
